#!/usr/bin/env bash
#vblkrmbkm
while read -r line; do
 username=$(echo "$line" | cut -d: -f1)
 uid=$(echo "$line" | cut -d: -f3)
 directory=$(echo "$line" | cut -d: -f6)
 echo "$username:$uid:$directory"
done < /etc/passwd
