#!/usr/bin/env bash
#comment
Hour=0
while ((Hour<=12)); do
    echo "Hour: $Hour"
    Minute=1
    while ((Minute<60)); do
        echo $Minute
        ((Minute++))
    done
    ((Hour++))
done | head -n 70
