#!/usr/bin/env bash
#ebrbrt

# Trap SIGTERM signal and display message instead of terminating
trap "echo 'I am invincible!!!'" TERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
